### ISSUE TITLE
Blood Altar Crashes game and will not work

### ISSUE THREAD

**Issue by Mick83Mack** [PhoenixTeamMC/Running-Red-2-Vampire-Money#50]
So I am at the part where you build a blood altar, when I turn in the quest it crashed my game. I went back in and now the Blood Altar does not actually hold any blood no matter what I do. I threw out that altar then spawned a new one in, that did not work, I also crafted a new one and that did not work. I cannot use the blood altar. The blood appears in it and then it disappears within seconds with or without an item in the altar.

**Comment by Gideonseymour** [comment]
Try just continuing to fill it up. It's the internal buffer draining, and once that's full, it will start filling up like normal.

**Comment by Mick83Mack** [comment]
I did it for like 20 minutes and it just kept emptying I will try again though.
